apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "product"
  labels: 
    app: "product"
spec: 
  selector: 
    matchLabels: 
      app: "product"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "product"
    spec: 
      containers: 
        - 
          name: "product"
          image: "879772956301.dkr.ecr.ap-northeast-1.amazonaws.com/user09-product:latest"
          ports: 
            - 
              containerPort: 80
